"""Recria banco apos refatoracao

Revision ID: a0bcd9935e62
Revises: 
Create Date: 2026-01-14 01:14:22.171544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0bcd9935e62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome da empresa'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='Identificador único para URLs'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email principal'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Telefone com DDD'),
    sa.Column('document', sa.String(length=20), nullable=True, comment='CNPJ ou CPF'),
    sa.Column('plan', sa.String(length=50), nullable=False, comment='Plano de assinatura'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Tenant ativo ou suspenso'),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Configurações flexíveis do tenant'),
    sa.Column('n8n_instance_url', sa.String(length=500), nullable=True, comment='URL da instância n8n do cliente'),
    sa.Column('n8n_api_key', sa.Text(), nullable=True, comment='API key do n8n (criptografada)'),
    sa.Column('n8n_provisioned', sa.Boolean(), nullable=False, comment='Se instância n8n foi provisionada'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('agent_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='Agente ativo globalmente'),
    sa.Column('agent_name', sa.String(length=100), nullable=False, comment='Nome do agente'),
    sa.Column('agent_role', sa.String(length=255), nullable=False, comment='Papel/função do agente'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Nome da empresa (para o prompt)'),
    sa.Column('company_description', sa.Text(), nullable=True, comment='Descrição da empresa/serviços'),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=False, comment='Respeitar horário de funcionamento'),
    sa.Column('schedule_start', sa.Time(), nullable=True, comment='Hora início atendimento'),
    sa.Column('schedule_end', sa.Time(), nullable=True, comment='Hora fim atendimento'),
    sa.Column('schedule_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Dias da semana (1=Seg, 7=Dom)'),
    sa.Column('schedule_timezone', sa.String(length=50), nullable=False, comment='Timezone'),
    sa.Column('outside_hours_message', sa.Text(), nullable=True, comment='Mensagem fora do horário'),
    sa.Column('base_prompt', sa.Text(), nullable=True, comment='Prompt base do agente'),
    sa.Column('greeting_prompt', sa.Text(), nullable=True, comment='Prompt para primeira mensagem'),
    sa.Column('qualification_prompt', sa.Text(), nullable=True, comment='Prompt para qualificação de leads'),
    sa.Column('objection_prompt', sa.Text(), nullable=True, comment='Prompt para tratamento de objeções'),
    sa.Column('closing_prompt', sa.Text(), nullable=True, comment='Prompt para fechamento'),
    sa.Column('max_messages_before_human', sa.Integer(), nullable=False, comment='Máximo de mensagens antes de chamar humano'),
    sa.Column('response_delay_seconds', sa.Integer(), nullable=False, comment='Delay antes de responder (simula digitação)'),
    sa.Column('auto_qualify_score', sa.Integer(), nullable=False, comment='Score mínimo para qualificar automaticamente'),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Configurações extras'),
    sa.Column('keywords_human', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Keywords para transferir para humano'),
    sa.Column('keywords_stop', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Keywords para pausar bot'),
    sa.Column('llm_provider', sa.String(length=50), nullable=False, comment='Provider: anthropic, openai'),
    sa.Column('llm_model', sa.String(length=100), nullable=False, comment='Modelo a usar'),
    sa.Column('llm_temperature', sa.Float(), nullable=False, comment='Temperatura do modelo'),
    sa.Column('llm_max_tokens', sa.Integer(), nullable=False, comment='Máximo de tokens na resposta'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_configs_id'), 'agent_configs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_configs_tenant_id'), 'agent_configs', ['tenant_id'], unique=True)
    op.create_table('pipelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome do pipeline'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Pipeline padrão do tenant'),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_id'), 'pipelines', ['id'], unique=False)
    op.create_index(op.f('ix_pipelines_tenant_id'), 'pipelines', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email do usuário'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Senha hasheada (bcrypt)'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Nome completo'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Telefone com DDD'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='URL do avatar'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Papel: owner, admin, manager, member'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Usuário ativo'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Superusuário (acesso global)'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='FK para tenant'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Último login'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'tenant_id', name='uq_user_email_tenant')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome do lead'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Telefone principal (WhatsApp)'),
    sa.Column('phone_secondary', sa.String(length=20), nullable=True, comment='Telefone secundário'),
    sa.Column('document', sa.String(length=20), nullable=True, comment='CPF ou CNPJ'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Nome da empresa (se B2B)'),
    sa.Column('company_position', sa.String(length=100), nullable=True, comment='Cargo na empresa'),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_number', sa.String(length=20), nullable=True),
    sa.Column('address_complement', sa.String(length=100), nullable=True),
    sa.Column('address_neighborhood', sa.String(length=100), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_zipcode', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status no funil'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='Origem do lead'),
    sa.Column('source_detail', sa.String(length=255), nullable=True, comment='Detalhe da origem (ex: nome da campanha)'),
    sa.Column('score', sa.Integer(), nullable=False, comment='Score de qualificação (0-100)'),
    sa.Column('temperature', sa.String(length=20), nullable=True, comment='Temperatura: cold, warm, hot'),
    sa.Column('interest', sa.String(length=255), nullable=True, comment='Produto/serviço de interesse'),
    sa.Column('budget', sa.Float(), nullable=True, comment='Orçamento estimado'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Observações gerais'),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Campos personalizados'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Tags/etiquetas'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True, comment='Usuário responsável'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Usuário que criou'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True, comment='Último contato'),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True, comment='Data de conversão'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assigned_to_id'), 'leads', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index('ix_leads_tenant_email', 'leads', ['tenant_id', 'email'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_index('ix_leads_tenant_phone', 'leads', ['tenant_id', 'phone'], unique=False)
    op.create_index('ix_leads_tenant_status', 'leads', ['tenant_id', 'status'], unique=False)
    op.create_table('stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False, comment='Ordem no pipeline (0, 1, 2...)'),
    sa.Column('color', sa.String(length=20), nullable=False, comment='Cor da coluna (hex)'),
    sa.Column('is_won', sa.Boolean(), nullable=False, comment='Stage de vitória (fechou negócio)'),
    sa.Column('is_lost', sa.Boolean(), nullable=False, comment='Stage de perda'),
    sa.Column('auto_probability', sa.Integer(), nullable=True, comment='Probabilidade automática (0-100%)'),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_id'), 'stages', ['id'], unique=False)
    op.create_index(op.f('ix_stages_pipeline_id'), 'stages', ['pipeline_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Telefone do contato (WhatsApp)'),
    sa.Column('contact_name', sa.String(length=255), nullable=True, comment='Nome do contato (do WhatsApp ou Lead)'),
    sa.Column('contact_avatar_url', sa.String(length=500), nullable=True, comment='URL do avatar'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Conversa ativa'),
    sa.Column('is_bot_active', sa.Boolean(), nullable=False, comment='Bot (Laura) está ativo nesta conversa'),
    sa.Column('is_unread', sa.Boolean(), nullable=False, comment='Tem mensagens não lidas'),
    sa.Column('unread_count', sa.Integer(), nullable=False, comment='Quantidade de mensagens não lidas'),
    sa.Column('last_message_text', sa.String(length=500), nullable=True, comment='Preview da última mensagem'),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True, comment='Data da última mensagem'),
    sa.Column('last_message_direction', sa.String(length=20), nullable=True, comment='Direção da última mensagem'),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True, comment='Atendente responsável'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Dados extras da conversa'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Tags da conversa'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True, comment='Lead vinculado'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_assigned_to_id'), 'conversations', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_lead_id'), 'conversations', ['lead_id'], unique=False)
    op.create_index(op.f('ix_conversations_phone'), 'conversations', ['phone'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_index('ix_conversations_tenant_last_message', 'conversations', ['tenant_id', 'last_message_at'], unique=False)
    op.create_index('ix_conversations_tenant_phone', 'conversations', ['tenant_id', 'phone'], unique=True)
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Título do deal'),
    sa.Column('value', sa.Float(), nullable=False, comment='Valor do negócio (R$)'),
    sa.Column('probability', sa.Integer(), nullable=False, comment='Probabilidade de fechamento (0-100%)'),
    sa.Column('expected_close_date', sa.DateTime(timezone=True), nullable=True, comment='Data esperada de fechamento'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False, comment='Posição dentro do stage'),
    sa.Column('is_won', sa.Boolean(), nullable=False),
    sa.Column('is_lost', sa.Boolean(), nullable=False),
    sa.Column('lost_reason', sa.String(length=255), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('won_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lost_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_assigned_to_id'), 'deals', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index(op.f('ix_deals_lead_id'), 'deals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_deals_pipeline_id'), 'deals', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_deals_stage_id'), 'deals', ['stage_id'], unique=False)
    op.create_index(op.f('ix_deals_tenant_id'), 'deals', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True, comment='ID da mensagem no Z-API/WhatsApp'),
    sa.Column('content', sa.Text(), nullable=True, comment='Texto da mensagem'),
    sa.Column('message_type', sa.String(length=50), nullable=False, comment='Tipo: text, image, audio, etc'),
    sa.Column('direction', sa.String(length=20), nullable=False, comment='inbound ou outbound'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status de envio'),
    sa.Column('media_url', sa.String(length=1000), nullable=True, comment='URL da mídia'),
    sa.Column('media_mime_type', sa.String(length=100), nullable=True, comment='MIME type da mídia'),
    sa.Column('media_filename', sa.String(length=255), nullable=True, comment='Nome do arquivo'),
    sa.Column('sent_by_id', sa.UUID(), nullable=True, comment='Usuário que enviou (se manual)'),
    sa.Column('sent_by_bot', sa.Boolean(), nullable=False, comment='Enviada pelo bot (Laura)'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Dados brutos do webhook'),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('whatsapp_timestamp', sa.DateTime(timezone=True), nullable=True, comment='Timestamp original do WhatsApp'),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_external_id', 'messages', ['external_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index('ix_messages_external_id', table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_deals_tenant_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_stage_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_pipeline_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_lead_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_assigned_to_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index('ix_conversations_tenant_phone', table_name='conversations')
    op.drop_index('ix_conversations_tenant_last_message', table_name='conversations')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_phone'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_lead_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_assigned_to_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_stages_pipeline_id'), table_name='stages')
    op.drop_index(op.f('ix_stages_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index('ix_leads_tenant_status', table_name='leads')
    op.drop_index('ix_leads_tenant_phone', table_name='leads')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index('ix_leads_tenant_email', table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pipelines_tenant_id'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_id'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_agent_configs_tenant_id'), table_name='agent_configs')
    op.drop_index(op.f('ix_agent_configs_id'), table_name='agent_configs')
    op.drop_table('agent_configs')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###

