"""Add appointments table

Revision ID: eefcb37bdbcd
Revises: a0bcd9935e62
Create Date: 2026-01-20 17:00:16.457929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eefcb37bdbcd'
down_revision = 'a0bcd9935e62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Título do agendamento'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descrição detalhada'),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False, comment='Data/hora de início'),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False, comment='Data/hora de término'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: pending, confirmed, cancelled, completed, no_show'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='Origem: ai, human_app, human_admin, whatsapp'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='Funcionário responsável'),
    sa.Column('lead_id', sa.UUID(), nullable=True, comment='Lead vinculado (opcional)'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Usuário que criou o agendamento'),
    sa.Column('client_name', sa.String(length=255), nullable=True, comment='Nome do cliente (se não tiver lead)'),
    sa.Column('client_phone', sa.String(length=20), nullable=True, comment='Telefone do cliente'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Observações'),
    sa.Column('location', sa.String(length=500), nullable=True, comment='Local/endereço da visita'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='Data de cancelamento'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Data de conclusão'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_employee_date', 'appointments', ['employee_id', 'start_datetime'], unique=False)
    op.create_index(op.f('ix_appointments_employee_id'), 'appointments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_lead_id'), 'appointments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_appointments_start_datetime'), 'appointments', ['start_datetime'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index('ix_appointments_tenant_date', 'appointments', ['tenant_id', 'start_datetime'], unique=False)
    op.create_index('ix_appointments_tenant_employee', 'appointments', ['tenant_id', 'employee_id'], unique=False)
    op.create_index(op.f('ix_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_tenant_id'), table_name='appointments')
    op.drop_index('ix_appointments_tenant_employee', table_name='appointments')
    op.drop_index('ix_appointments_tenant_date', table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_start_datetime'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_lead_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_employee_id'), table_name='appointments')
    op.drop_index('ix_appointments_employee_date', table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###

